import { describe, expect, it } from "vitest";
import { buildWebUiHtml } from "./web-app.js";

describe("lib/ui/web-app", () => {
  it("renders core dashboard sections and actions", () => {
    const html = buildWebUiHtml();
    expect(html).toContain("SYNX.js - Mission Control");
    expect(html).toContain('data-view="overview"');
    expect(html).toContain('data-view="tasks"');
    expect(html).toContain('data-view="board"');
    expect(html).toContain('data-view="review"');
    expect(html).toContain('data-view="detail"');
    expect(html).toContain('data-view="live"');
    expect(html).toContain('data-view="analytics"');
    expect(html).toContain('id="web-command-form"');
    expect(html).toContain('id="web-command-input"');
    expect(html).toContain('id="web-command-mode"');
    expect(html).toContain('id="web-command-log"');
    expect(html).toContain("/api/command");
    expect(html).toContain("/api/overview");
    expect(html).toContain("/api/metrics/advanced");
    expect(html).toContain('setInterval(() => {');
    expect(html).toContain('requestRender("poll");');
    expect(html).toContain("refreshGlobalSnapshot()");
    expect(html).toContain("/api/stream");
    expect(html).toContain("/approve");
    expect(html).toContain("/reprove");
    expect(html).toContain("/cancel");
    expect(html).toContain("/api/runtime/");
    expect(html).toContain("Cost Curve (30d)");
    expect(html).toContain("Token Curve (30d)");
    expect(html).toContain("Duration Curve (30d)");
    expect(html).toContain("overview-root");
  });

  it("includes phase 5 UX hardening markers for loading, accessibility, and retries", () => {
    const html = buildWebUiHtml();
    expect(html).toContain('class="skip-link"');
    expect(html).toContain('id="content" role="region" aria-live="polite" aria-busy="false"');
    expect(html).toContain('id="feedback" class="feedback" role="status" aria-live="polite"');
    expect(html).toContain("showLoading(");
    expect(html).toContain("renderedViews");
    expect(html).toContain("setTextIfChanged(");
    expect(html).toContain("Loading task list...");
    expect(html).toContain('data-retry-render');
    expect(html).toContain('class="table-wrap"');
    expect(html).toContain('caption class="sr-only"');
    expect(html).toContain('class="chart-grid"');
    expect(html).toContain("renderCurveChart(");
    expect(html).toContain("@media (max-width: 940px)");
    expect(html).toContain("@media (max-width: 640px)");
    expect(html).toContain("reviewRenderedKey");
    expect(html).toContain("liveRenderedCount");
    expect(html).toContain('id="review-root"');
    expect(html).toContain('id="live-root"');
    expect(html).toContain('id="review-reason"');
    expect(html).toContain('id="review-rollback"');
    expect(html).toContain('data-task-id="');
    expect(html).toContain('target.closest("[data-task-action]")');
    expect(html).toContain('target.closest("[data-open-task]")');
    expect(html).toContain('target.closest("[data-runtime-action]")');
    expect(html).toContain("Task moved to waiting_human and needs your decision (");
    expect(html).toContain("Task state changed (");
    expect(html).toContain("boardColumnForTask(");
    expect(html).toContain("renderBoard()");
    expect(html).toContain("board-columns");
    expect(html).toContain("Loading agent board...");
    expect(html).toContain('data-theme-option="light"');
    expect(html).toContain('data-theme-option="system"');
    expect(html).toContain('data-theme-option="dark"');
    expect(html).toContain("applyThemePreference(");
    expect(html).toContain("loadThemePreference(");
    expect(html).toContain("bindSystemThemeSync(");
    expect(html).toContain("requestRender(");
    expect(html).toContain("executeWebCommand(");
    expect(html).toContain("pushCommandLog(");
    expect(html).toContain("Intl.NumberFormat");
    expect(html).toContain("Intl.DateTimeFormat");
    expect(html).toContain("currencyFormatter");
    expect(html).toContain("fmtDateTime(");
    expect(html).not.toContain("UI build:");
    expect(html).toContain('class="logo-ascii"');
    expect(html).toContain("SYNX.js - Mission Control");
    expect(html).toContain("--synx-cyan");
    expect(html).toContain('html[data-theme="dark"]');
  });
});
